// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqdCWKTmKSKGG5fWiwSBT7ttvXJJssDw',
    appId: '1:1010354376128:web:d3873ed49bb4bf91d3cc25',
    messagingSenderId: '1010354376128',
    projectId: 'ica12-b13d3',
    authDomain: 'ica12-b13d3.firebaseapp.com',
    storageBucket: 'ica12-b13d3.firebasestorage.app',
    measurementId: 'G-ER60RPZNHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbwAW84t2wlufhn4AxwPdbHHZkzPFfJI',
    appId: '1:1010354376128:android:3a8d5b802f8f3cdbd3cc25',
    messagingSenderId: '1010354376128',
    projectId: 'ica12-b13d3',
    storageBucket: 'ica12-b13d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYn7ZCdOwN1EDe2x1YQYa7nSpgTZiWa70',
    appId: '1:1010354376128:ios:9aec2a516fd93840d3cc25',
    messagingSenderId: '1010354376128',
    projectId: 'ica12-b13d3',
    storageBucket: 'ica12-b13d3.firebasestorage.app',
    iosBundleId: 'com.example.ica12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYn7ZCdOwN1EDe2x1YQYa7nSpgTZiWa70',
    appId: '1:1010354376128:ios:9aec2a516fd93840d3cc25',
    messagingSenderId: '1010354376128',
    projectId: 'ica12-b13d3',
    storageBucket: 'ica12-b13d3.firebasestorage.app',
    iosBundleId: 'com.example.ica12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDqdCWKTmKSKGG5fWiwSBT7ttvXJJssDw',
    appId: '1:1010354376128:web:3b8ea4d45414e3b4d3cc25',
    messagingSenderId: '1010354376128',
    projectId: 'ica12-b13d3',
    authDomain: 'ica12-b13d3.firebaseapp.com',
    storageBucket: 'ica12-b13d3.firebasestorage.app',
    measurementId: 'G-F6LNLY7FTX',
  );
}
